
package inventory.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DALFault", targetNamespace = "http://ws.inventory/")
public class DALException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DalFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DALException(String message, DalFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DALException(String message, DalFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: inventory.ws.DalFault
     */
    public DalFault getFaultInfo() {
        return faultInfo;
    }

}
